<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>neon</string>
	</array>
	<key>name</key>
	<string>Neon</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(#)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.neon</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s+)(days|day|hours|hour|minutes|minute|weeks|week|TRUE|True|true|FALSE|False|false|YES|Yes|yes|NO|No|no|ON|On|on|OFF|Off|off|NULL|Null|null)(\s*$)</string>
			<key>name</key>
			<string>constant.language.neon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.neon</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.other.neon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.neon</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([a-zA-Z._-]*)(:)(?=\s*\S+)</string>
			<key>name</key>
			<string>keyword.operator.neon</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.neon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>operator.neon</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([a-zA-Z._-]*)(:)</string>
			<key>name</key>
			<string>keyword.operator.neon</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.neon</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^?\s(-)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(@\w+)</string>
			<key>name</key>
			<string>support.class.neon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(["])</string>
			<key>end</key>
			<string>(["])</string>
			<key>name</key>
			<string>string.quoted.double.neon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(['])</string>
			<key>end</key>
			<string>(['])</string>
			<key>name</key>
			<string>string.quoted.single.neon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(%.*?%)</string>
					<key>name</key>
					<string>variable.parameter.neon</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.neon</string>
</dict>
</plist>